#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class Committente
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private decimal? _totaleFattureVendita;
		public virtual decimal? TotaleFattureVendita
		{
			get
			{
				return this._totaleFattureVendita;
			}
			set
			{
				this._totaleFattureVendita = value;
			}
		}
		
		private string _stato;
		public virtual string Stato
		{
			get
			{
				return this._stato;
			}
			set
			{
				this._stato = value;
			}
		}
		
		private decimal? _totaleIncassi;
		public virtual decimal? TotaleIncassi
		{
			get
			{
				return this._totaleIncassi;
			}
			set
			{
				this._totaleIncassi = value;
			}
		}
		
		private string _note;
		public virtual string Note
		{
			get
			{
				return this._note;
			}
			set
			{
				this._note = value;
			}
		}
		
		private int _commessaId;
		public virtual int CommessaId
		{
			get
			{
				return this._commessaId;
			}
			set
			{
				this._commessaId = value;
			}
		}
		
		private int _anagraficaCommittenteId;
		public virtual int AnagraficaCommittenteId
		{
			get
			{
				return this._anagraficaCommittenteId;
			}
			set
			{
				this._anagraficaCommittenteId = value;
			}
		}
		
		private Commessa _commessa;
		public virtual Commessa Commessa
		{
			get
			{
				return this._commessa;
			}
			set
			{
				this._commessa = value;
			}
		}
		
		private AnagraficaCommittente _anagraficaCommittente;
		public virtual AnagraficaCommittente AnagraficaCommittente
		{
			get
			{
				return this._anagraficaCommittente;
			}
			set
			{
				this._anagraficaCommittente = value;
			}
		}
		
		private IList<FatturaVendita> _fatturaVenditas = new List<FatturaVendita>();
		public virtual IList<FatturaVendita> FatturaVenditas
		{
			get
			{
				return this._fatturaVenditas;
			}
		}
		
	}
}
#pragma warning restore 1591
