#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class FatturaVendita
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int _clienteId;
		public virtual int ClienteId
		{
			get
			{
				return this._clienteId;
			}
			set
			{
				this._clienteId = value;
			}
		}
		
		private DateTime? _data;
		public virtual DateTime? Data
		{
			get
			{
				return this._data;
			}
			set
			{
				this._data = value;
			}
		}
		
		private string _numero;
		public virtual string Numero
		{
			get
			{
				return this._numero;
			}
			set
			{
				this._numero = value;
			}
		}
		
		private string _tipoPagamento;
		public virtual string TipoPagamento
		{
			get
			{
				return this._tipoPagamento;
			}
			set
			{
				this._tipoPagamento = value;
			}
		}
		
		private string _descrizione;
		public virtual string Descrizione
		{
			get
			{
				return this._descrizione;
			}
			set
			{
				this._descrizione = value;
			}
		}
		
		private decimal? _imponibile;
		public virtual decimal? Imponibile
		{
			get
			{
				return this._imponibile;
			}
			set
			{
				this._imponibile = value;
			}
		}
		
		private decimal? _iVA;
		public virtual decimal? IVA
		{
			get
			{
				return this._iVA;
			}
			set
			{
				this._iVA = value;
			}
		}
		
		private decimal? _totale;
		public virtual decimal? Totale
		{
			get
			{
				return this._totale;
			}
			set
			{
				this._totale = value;
			}
		}
		
		private string _scadenzaPagamento;
		public virtual string ScadenzaPagamento
		{
			get
			{
				return this._scadenzaPagamento;
			}
			set
			{
				this._scadenzaPagamento = value;
			}
		}
		
		private Cliente _cliente;
		public virtual Cliente Cliente
		{
			get
			{
				return this._cliente;
			}
			set
			{
				this._cliente = value;
			}
		}
		
		private IList<Liquidazione> _liquidaziones = new List<Liquidazione>();
		public virtual IList<Liquidazione> Liquidaziones
		{
			get
			{
				return this._liquidaziones;
			}
		}
		
	}
}
#pragma warning restore 1591
