#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class Fornitore
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int _commessaId;
		public virtual int CommessaId
		{
			get
			{
				return this._commessaId;
			}
			set
			{
				this._commessaId = value;
			}
		}
		
		private string _ragioneSociale;
		public virtual string RagioneSociale
		{
			get
			{
				return this._ragioneSociale;
			}
			set
			{
				this._ragioneSociale = value;
			}
		}
		
		private string _indirizzo;
		public virtual string Indirizzo
		{
			get
			{
				return this._indirizzo;
			}
			set
			{
				this._indirizzo = value;
			}
		}
		
		private string _cAP;
		public virtual string CAP
		{
			get
			{
				return this._cAP;
			}
			set
			{
				this._cAP = value;
			}
		}
		
		private string _comune;
		public virtual string Comune
		{
			get
			{
				return this._comune;
			}
			set
			{
				this._comune = value;
			}
		}
		
		private string _provincia;
		public virtual string Provincia
		{
			get
			{
				return this._provincia;
			}
			set
			{
				this._provincia = value;
			}
		}
		
		private string _telefono;
		public virtual string Telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				this._telefono = value;
			}
		}
		
		private string _mobile;
		public virtual string Mobile
		{
			get
			{
				return this._mobile;
			}
			set
			{
				this._mobile = value;
			}
		}
		
		private string _fax;
		public virtual string Fax
		{
			get
			{
				return this._fax;
			}
			set
			{
				this._fax = value;
			}
		}
		
		private string _email;
		public virtual string Email
		{
			get
			{
				return this._email;
			}
			set
			{
				this._email = value;
			}
		}
		
		private string _partitaIva;
		public virtual string PartitaIva
		{
			get
			{
				return this._partitaIva;
			}
			set
			{
				this._partitaIva = value;
			}
		}
		
		private string _codice;
		public virtual string Codice
		{
			get
			{
				return this._codice;
			}
			set
			{
				this._codice = value;
			}
		}
		
		private string _codiceCatastale;
		public virtual string CodiceCatastale
		{
			get
			{
				return this._codiceCatastale;
			}
			set
			{
				this._codiceCatastale = value;
			}
		}
		
		private decimal? _totaleFattureAcquisto;
		public virtual decimal? TotaleFattureAcquisto
		{
			get
			{
				return this._totaleFattureAcquisto;
			}
			set
			{
				this._totaleFattureAcquisto = value;
			}
		}
		
		private string _stato;
		public virtual string Stato
		{
			get
			{
				return this._stato;
			}
			set
			{
				this._stato = value;
			}
		}
		
		private decimal? _totalePagamenti;
		public virtual decimal? TotalePagamenti
		{
			get
			{
				return this._totalePagamenti;
			}
			set
			{
				this._totalePagamenti = value;
			}
		}
		
		private string _localita;
		public virtual string Localita
		{
			get
			{
				return this._localita;
			}
			set
			{
				this._localita = value;
			}
		}
		
		private string _note;
		public virtual string Note
		{
			get
			{
				return this._note;
			}
			set
			{
				this._note = value;
			}
		}
		
		private Commessa _commessa;
		public virtual Commessa Commessa
		{
			get
			{
				return this._commessa;
			}
			set
			{
				this._commessa = value;
			}
		}
		
		private IList<FatturaAcquisto> _fatturaAcquistos = new List<FatturaAcquisto>();
		public virtual IList<FatturaAcquisto> FatturaAcquistos
		{
			get
			{
				return this._fatturaAcquistos;
			}
		}
		
	}
}
#pragma warning restore 1591
