#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class NotaCredito
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int _fornitoreId;
		public virtual int FornitoreId
		{
			get
			{
				return this._fornitoreId;
			}
			set
			{
				this._fornitoreId = value;
			}
		}
		
		private DateTime? _data;
		public virtual DateTime? Data
		{
			get
			{
				return this._data;
			}
			set
			{
				this._data = value;
			}
		}
		
		private decimal? _imponibile;
		public virtual decimal? Imponibile
		{
			get
			{
				return this._imponibile;
			}
			set
			{
				this._imponibile = value;
			}
		}
		
		private string _note;
		public virtual string Note
		{
			get
			{
				return this._note;
			}
			set
			{
				this._note = value;
			}
		}
		
		private string _descrizione;
		public virtual string Descrizione
		{
			get
			{
				return this._descrizione;
			}
			set
			{
				this._descrizione = value;
			}
		}
		
		private string _numero;
		public virtual string Numero
		{
			get
			{
				return this._numero;
			}
			set
			{
				this._numero = value;
			}
		}
		
		private decimal? _iVA;
		public virtual decimal? IVA
		{
			get
			{
				return this._iVA;
			}
			set
			{
				this._iVA = value;
			}
		}
		
		private decimal? _totale;
		public virtual decimal? Totale
		{
			get
			{
				return this._totale;
			}
			set
			{
				this._totale = value;
			}
		}
		
		private Fornitore _fornitore;
		public virtual Fornitore Fornitore
		{
			get
			{
				return this._fornitore;
			}
			set
			{
				this._fornitore = value;
			}
		}
		
		private IList<Reso> _resos = new List<Reso>();
		public virtual IList<Reso> Resos
		{
			get
			{
				return this._resos;
			}
		}
		
	}
}
#pragma warning restore 1591
