#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class PagamentoUnificatoFatturaAcquisto
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int _fatturaAcquistoId;
		public virtual int FatturaAcquistoId
		{
			get
			{
				return this._fatturaAcquistoId;
			}
			set
			{
				this._fatturaAcquistoId = value;
			}
		}
		
		private int _pagamentoUnificatoId;
		public virtual int PagamentoUnificatoId
		{
			get
			{
				return this._pagamentoUnificatoId;
			}
			set
			{
				this._pagamentoUnificatoId = value;
			}
		}
		
		private decimal? _saldo;
		public virtual decimal? Saldo
		{
			get
			{
				return this._saldo;
			}
			set
			{
				this._saldo = value;
			}
		}
		
		private string _note;
		public virtual string Note
		{
			get
			{
				return this._note;
			}
			set
			{
				this._note = value;
			}
		}
		
		private string _transazionePagamento;
		public virtual string TransazionePagamento
		{
			get
			{
				return this._transazionePagamento;
			}
			set
			{
				this._transazionePagamento = value;
			}
		}
		
		private FatturaAcquisto _fatturaAcquisto;
		public virtual FatturaAcquisto FatturaAcquisto
		{
			get
			{
				return this._fatturaAcquisto;
			}
			set
			{
				this._fatturaAcquisto = value;
			}
		}
		
		private PagamentoUnificato _pagamentoUnificato;
		public virtual PagamentoUnificato PagamentoUnificato
		{
			get
			{
				return this._pagamentoUnificato;
			}
			set
			{
				this._pagamentoUnificato = value;
			}
		}
		
	}
}
#pragma warning restore 1591
