#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class ReportJob
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private DateTime? _creazione;
		public virtual DateTime? Creazione
		{
			get
			{
				return this._creazione;
			}
			set
			{
				this._creazione = value;
			}
		}
		
		private string _codice;
		public virtual string Codice
		{
			get
			{
				return this._codice;
			}
			set
			{
				this._codice = value;
			}
		}
		
		private string _denominazione;
		public virtual string Denominazione
		{
			get
			{
				return this._denominazione;
			}
			set
			{
				this._denominazione = value;
			}
		}
		
		private string _tipo;
		public virtual string Tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				this._tipo = value;
			}
		}
		
		private string _codiceFornitore;
		public virtual string CodiceFornitore
		{
			get
			{
				return this._codiceFornitore;
			}
			set
			{
				this._codiceFornitore = value;
			}
		}
		
		private DateTime? _elaborazione;
		public virtual DateTime? Elaborazione
		{
			get
			{
				return this._elaborazione;
			}
			set
			{
				this._elaborazione = value;
			}
		}
		
		private string _note;
		public virtual string Note
		{
			get
			{
				return this._note;
			}
			set
			{
				this._note = value;
			}
		}
		
		private string _nomeFile;
		public virtual string NomeFile
		{
			get
			{
				return this._nomeFile;
			}
			set
			{
				this._nomeFile = value;
			}
		}
		
		private int _aziendaId;
		public virtual int AziendaId
		{
			get
			{
				return this._aziendaId;
			}
			set
			{
				this._aziendaId = value;
			}
		}
		
		private string _codiceCommittente;
		public virtual string CodiceCommittente
		{
			get
			{
				return this._codiceCommittente;
			}
			set
			{
				this._codiceCommittente = value;
			}
		}
		
		private Azienda _azienda;
		public virtual Azienda Azienda
		{
			get
			{
				return this._azienda;
			}
			set
			{
				this._azienda = value;
			}
		}
		
	}
}
#pragma warning restore 1591
