#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class SAL
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int _commessaId;
		public virtual int CommessaId
		{
			get
			{
				return this._commessaId;
			}
			set
			{
				this._commessaId = value;
			}
		}
		
		private DateTime? _data;
		public virtual DateTime? Data
		{
			get
			{
				return this._data;
			}
			set
			{
				this._data = value;
			}
		}
		
		private decimal? _totaleFattureAcquisto;
		public virtual decimal? TotaleFattureAcquisto
		{
			get
			{
				return this._totaleFattureAcquisto;
			}
			set
			{
				this._totaleFattureAcquisto = value;
			}
		}
		
		private decimal? _totaleFattureVendita;
		public virtual decimal? TotaleFattureVendita
		{
			get
			{
				return this._totaleFattureVendita;
			}
			set
			{
				this._totaleFattureVendita = value;
			}
		}
		
		private string _denominazione;
		public virtual string Denominazione
		{
			get
			{
				return this._denominazione;
			}
			set
			{
				this._denominazione = value;
			}
		}
		
		private string _codice;
		public virtual string Codice
		{
			get
			{
				return this._codice;
			}
			set
			{
				this._codice = value;
			}
		}
		
		private decimal? _totaleIncassi;
		public virtual decimal? TotaleIncassi
		{
			get
			{
				return this._totaleIncassi;
			}
			set
			{
				this._totaleIncassi = value;
			}
		}
		
		private decimal? _totalePagamenti;
		public virtual decimal? TotalePagamenti
		{
			get
			{
				return this._totalePagamenti;
			}
			set
			{
				this._totalePagamenti = value;
			}
		}
		
		private string _stato;
		public virtual string Stato
		{
			get
			{
				return this._stato;
			}
			set
			{
				this._stato = value;
			}
		}
		
		private string _note;
		public virtual string Note
		{
			get
			{
				return this._note;
			}
			set
			{
				this._note = value;
			}
		}
		
		private Commessa _commessa;
		public virtual Commessa Commessa
		{
			get
			{
				return this._commessa;
			}
			set
			{
				this._commessa = value;
			}
		}
		
	}
}
#pragma warning restore 1591
